/* DO NOT EDIT THIS FILE - it is machine generated */

#include  <jni.h>

/* Header for class com_demo_jnidemo_JNI */

#ifndef _Included_com_demo_jnidemo_JNI

#define _Included_com_demo_jnidemo_JNI

#ifdef __cplusplus

extern"C"{

#endif

/*

* Class:    com_demo_jnidemo_JNI

* Method:    getInt

* Signature: ()I

*/

JNIEXPORT jint JNICALL Java_com_demo_jnidemo_JNI_getInt

(JNIEnv *, jobject);

#ifdef __cplusplus

}

#endif

#endif
